### ISSUE TITLE
ERR error="invalid country code: could not infer country code from store front" success=false

### ISSUE THREAD

**Issue by 24h7d** [majd/ipatool#131]
### What happened?

when I successfully log in and try to search for the application it always shows this error
ERR error="invalid country code: could not infer country code from store front" success=false

Does anyone have the same issue here?

### Version

2.0.0

**Comment by crazyi** [comment]
This error occurs as the flag --country had been deprecated.
But I think the deprecated flags are useful because some apps were banned at local appstore and the only way to  download is to change the appstore to another country.
So I strongly recommend that the author @majd can restore the deprecated flags.

**Comment by majd** [comment]
@24h7d What operating system are you using the tool on?

**Comment by majd** [comment]
> This error occurs as the flag --country had been deprecated.
But I think the deprecated flags are useful because some apps were banned at local appstore and the only way to download is to change the appstore to another country.
So I strongly recommend that the author @majd can restore the deprecated flags.

@crazyi The fact that you can search for an app by specifying the country code does not mean that you can download it using an Apple ID that belongs to a different country. The app *has* to exist in the country of the authenticated Apple ID. That was the point of the change, to simplify the user flow. See #130.

If you absolutely need to search for an app in another store without authenticating, you can use the iTunes API directly. 
```sh
$ curl -s 'http://itunes.apple.com/search?term=TestFlight&media=software&country=US' | jq -r '.results | first | .trackName'
TestFlight
```

**Comment by 24h7d** [comment]
Im using macbook pro monterey

**Comment by majd** [comment]
@24h7d Please use the Keychain Access app on your MacBook to search for an application password labeled `ipatool2.service`. It should be in the login keychain. Once you find it, double click on it check the "show password" box. Please share the `storeFront` value you find there.

Please note that the string that contain sensitive data so make sure you don't share the entire string here and only the `storeFront` value.

**Comment by 24h7d** [comment]
I only found ipatool-auth.service in my keychain access

**Comment by majd** [comment]
> I only found ipatool-auth.service in my keychain access
> […](#)

That should be the one.

**Comment by 24h7d** [comment]
But when I click show password there is no storefront just my plaintext
password

**Comment by majd** [comment]
The value for the keychain item should be a JSON blob with multiple keys. Keys include `email`, `name`, `directoryServicesIdentifier`, `storeFront` and other keys. See [appstore_login.go#L117](https://github.com/majd/ipatool/blob/main/pkg/appstore/appstore_login.go#L117). Are you missing the `storeFront` key there?

**Comment by 24h7d** [comment]
Yes, the value just my apple id password in json format

**Comment by nasaa0528** [comment]
I have same error. Tested on debian 6.0.0 and macOS Ventura. Keyring file is being created, storeFront exists but error says
`ERR error="invalid country code: could not infer country code from store front" success=false`

**Comment by 24h7d** [comment]
The problem in authentication process.
I fixed this issue by re login with :
ipatool auth -e <email>

Then input the password

Pop up on mac to authorize and the OTP number to be be input to the ipatool

----
Use -e instead -email in auth command

**Comment by nasaa0528** [comment]
The above doesn't solve my problem. Tried deleting ipatool.service keyring, and re-authenticated. I'm still having same error. 
My value is `storeFront: 143592-2,34`.

**Comment by nasaa0528** [comment]
Fixed the problem by authenticating with different apple account. Probably, the initial appleId I've used might have different country storeFront, therefore, it was giving me the error.

**Comment by majd** [comment]
@nasaa0528 I believe that is due to Mongolia missing from the storefront list. It should be fixed in #134 and the fix was shipped with [version 2.0.1](https://github.com/majd/ipatool/releases/tag/v2.0.1).

**Comment by spenkk** [comment]
Could you please add the following store front to the list since I can't use that app due to the same issue?

"storeFront":"143575-2,34" -> Albania

**Comment by majd** [comment]
@spenkk Added in #141.

**Comment by ddomino007** [comment]
I have the same error, region is PL
I could bypass this if the option wasn't deprecated
M1 MacBook Air Ventura 22D68
Terminal.app
nothing blocked no nothing

**Comment by sabrysmk** [comment]
@majd  Could you please add the following store front to the list since I can't use that app due to the same issue?

"storeFront":"143615-2,34" -> Georgia
