### ISSUE TITLE
failed to remove original file

### ISSUE THREAD

**Issue by DTD369** [majd/ipatool#243]
### What happened?

When I downloaded an IPA using IPATool, it completed with this error:
```
[Time] ERR error="failed to remove original file: remove C:\\Users\\<user>\\Downloads\\<app>.ipa: The process cannot access the file because it is being used by another process." success=false
```
When I checked the Downloads folder, I could see that there were the original IPA file and a TMP file. Since I had read the code, I understood that IPATool was meant to delete the original file and then rename the TMP file to the IPA file, but was unable to do the former since the file handle was still open. Of course, I can do the rest but it's annoying to do so every time.

### Version

v2.1.3 (latest)

### Relevant log output

```shell
D:\IPATool>ipatool download -b com.iYOK.BLEJoyStick -o "%USERPROFILE%\Downloads\BLE Joystick.ipa" --verbose
9:10AM INF enter passphrase to unlock "C:\\Users\\'\\.ipatool" (this is separate from your Apple ID password):
9:10AM DBG error="failed to remove original file: remove C:\\Users\\'\\Downloads\\BLE Joystick.ipa: The process cannot access the file because it is being used by another process."
9:10AM ERR error="failed to remove original file: remove C:\\Users\\'\\Downloads\\BLE Joystick.ipa: The process cannot access the file because it is being used by another process." success=false
```

**Comment by ksagameng2** [comment]
The bug was fixed but the latest release doesn't have it so build the source yourself and use that

**Comment by mikesTech** [comment]
https://github.com/majd/ipatool/issues/248 
this may apply to u @DTD369

**Comment by Milchkarl** [comment]
this issue still persists using the windows amd download on the latest version (2.3.0)
